[package]
name = "chatterbox-messages"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = { version = "1.0.95", default-features = false }
aws-config = { version = "1.5.16", default-features = false }
aws-sdk-dynamodb = { version = "1.65.0", default-features = false, features = [
  "rt-tokio",
  "rustls",
] }
aws-sdk-sqs = { version = "1.59.0", default-features = false, features = [
  "rt-tokio",
  "rustls",
] }
axum = { version = "0.8.1", default-features = false, features = [
  "http1",
  "tokio",
] }
chrono = { version = "0.4.39", default-features = false, features = ["serde"] }
jsonwebtoken = { version = "9.3.1", default-features = false, features = [
  "use_pem",
] }
serde = { version = "1.0.217", default-features = false }
socketioxide = { version = "0.16.1", default-features = false, features = [
  "extensions",
  "state",
  "tracing",
] }
tokio = { version = "1.43.0", default-features = false, features = [
  "macros",
  "rt-multi-thread",
] }
tower-http = { version = "0.6.2", default-features = false, features = [
  "cors",
  "trace",
] }
tracing = { version = "0.1.41", default-features = false }
tracing-subscriber = { version = "0.3.19", default-features = false, features = [
  "ansi",
] }

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
strip = true
